Fixed the movement bugs
dalbitresb12/zion-escape pull request #16
Opened 2020-11-20 17:35 UTC by amenes12

### Qué es lo que hace

Muestra adecuadamente los sprites de los personajes animados. 

### Por qué es necesario

Para una mejor experiencia visual dentro de nuestro juego 🎮.

### Issue(s) o PR(s) relacionados

Fixes #13

2020-11-20 19:04 UTC, FrowsyFrog requested changes
Muy bien! Me gustaron los cambios hechos y cómo está quedando! Creo que falta pulir un poco solo en algunos pequeños detalles. 👍  GJ

2020-11-20 19:04 UTC, FrowsyFrog commented on ZionEscape/MainActivity.h
> -      this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
Disculpa, ¿Cuál es la necesidad cambiar el AutoScaleDimensions y el ClientSize? Al hacerlo, creo que podrían presentarse problemas con la UI y el posicionamiento de imágenes, no estoy seguro. Pero de cualquier manera, ¿no se podría omitir el aumentar esos valores?

2020-11-20 19:04 UTC, FrowsyFrog commented on ZionEscape/MainActivity.h
> +      this->AnimationTimer->Interval = 50;
Prueba con el valor de 80, creo que se vería mucho mejor 😄

2020-11-20 19:04 UTC, FrowsyFrog commented on ZionEscape/MainActivity.h
> -      this->MovementTimer->Interval = 30;
Creo que sería mejor si se quedara en 30 o hasta en 20, ya que el Refresh para actualizar lo que se pinta en pantalla depende del intervalo entre ticks.

2020-11-20 19:04 UTC, FrowsyFrog commented on ZionEscape/MainActivity.h
> -      this->ClientSize = System::Drawing::Size(936, 624);
Igual que en lo de arriba, respecto a las escalas.

2020-11-20 19:04 UTC, FrowsyFrog commented on ZionEscape/MainActivity.h
> +  private: System::Windows::Forms::Timer^ AnimationTimer;
Solo para mantener el orden. Puedes colocar el AnimationTimer justo donde se declara el MovementTimer. 😄 

```csharp
    System::ComponentModel::IContainer^ components;
    System::Windows::Forms::Timer^ MovementTimer;
    System::Windows::Forms::Timer^ AnimationTimer;
```

2020-11-22 00:33 UTC, amenes12 commented on ZionEscape/MainActivity.h
> -      this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
Estoy en eso, esos cambios fueron sin querer. Disculpa, en seguida los revertiré.

2020-11-22 00:46 UTC, amenes12 commented
@FrowsyFrog @dalbitresb12 Devolví los valores a sus predeterminados e hice los cambios de posición solicitados, échenle un ojo y confirmen. 👀

2020-11-22 01:50 UTC, FrowsyFrog approved these changes
!Quedó muy bien el resultado! 👍

2020-11-22 04:00 UTC, merged