Added Message Box
dalbitresb12/zion-escape pull request #17
Opened 2020-11-20 22:40 UTC by FrowsyFrog

### Qué es lo que hace

Un cuadro de texto junto a su label aparece al presionar la letra `M`. Aparecerán todos los diálogos correspondientes a la conversación entre los corruptos y asesinos. Una vez que acaben, el cuadro se eliminará.

### Uso

Declarar que se activa el MessageBox (*En este ejemplo es al presionar M, pero esto debe ser cambiado a cuando llegue a cierta zona del mapa*)
```csharp
if (e->KeyCode == Keys::M) {
      this->game->StartMessagebox();
      this->game->SetMessage(this->MessageLabel);
      this->MessageTimer->Start();
      return;
    }
```
### Por qué es necesario

Es necesario para la negociación entre los corruptos y asesinos.

2020-11-20 23:16 UTC, dalbitresb12 requested changes
Está muy bien, solo son cambios de formato ligeros. 😄 

Eso sí, **siempre ten mucho cuidado** con el uso del `BitmapManager`. El uso correcto es como lo he detallado en los comentarios.

2020-11-20 23:16 UTC, dalbitresb12 commented on ZionEscape/MessageBox.h
> +  BitmapManager^ bmpManager;
La idea de no instanciar `BitmapManager` es evitar tener que guardarlo como atributo en las clases.

2020-11-20 23:16 UTC, dalbitresb12 commented on ZionEscape/MessageBox.h
> +    delete this->bmpManager;
Esto haría que se borre **todo** el `BitmapManager`, el cual es **único** en todo el programa. Dejaría a todas las otras clases sin un `BitmapManager` y también sin sus respectivas imágenes, ya que el `BitmapManager` es el que se encarga de eliminar todos los `Bitmaps` que tenga en su poder.

2020-11-20 23:16 UTC, dalbitresb12 commented on ZionEscape/MessageBox.h
> +  }
Aquí puedes obtener la instancia del `BitmapManager` y usarlo.

```suggestion
  void Draw(Graphics^ g) {
    BitmapManager^ bmpManager = BitmapManager::GetInstance();
    //Select the image and the position
    g->DrawImage(bmpManager->GetImage("assets\\sprites\\misc\\messagebox.png"), Point(101,230));
  }
```

Incluso, podrías hacerlo todo en una sola línea (pero se ve feo):

```suggestion
  void Draw(Graphics^ g) {
    //Select the image and the position
    g->DrawImage(BitmapManager::GetInstance()->GetImage("assets\\sprites\\misc\\messagebox.png"), Point(101,230));
  }
```

2020-11-20 23:16 UTC, dalbitresb12 commented on ZionEscape/MessageBox.h
> +  void SetLen(int value) {
Trata de poner el nombre completo, si no se entiende qué es realmente.

```suggestion
  void SetLength(int value) {
```

2020-11-20 23:16 UTC, dalbitresb12 commented on ZionEscape/MessageBox.h
> +  int counter, len, order, nextMessage;
Cambia `len` por `length`. Además, podría ser un `unsigned int` ya que es imposible que la longitud sea negativa.

2020-11-20 23:16 UTC, dalbitresb12 commented on ZionEscape/MessageBox.h
> +  void SetTxt(String^ txt) {
```suggestion
  void SetText(String^ txt) {
```

2020-11-20 23:16 UTC, dalbitresb12 commented on ZionEscape/Game.h
> +  void SetMessage(System::Windows::Forms::Label^ label) {
Seguramente debes poder evitar poner el `namespace`. Pruébalo.

```suggestion
  void SetMessage(Label^ label) {
```

2020-11-26 05:48 UTC, IzaYam approved these changes

2020-11-26 06:40 UTC, dalbitresb12 commented
Closed in favor of #33.

2020-11-26 06:40 UTC, closed without merging