Applied optimizations to map generator
dalbitresb12/zion-escape pull request #19
Opened 2020-11-21 05:14 UTC by dalbitresb12

### Qué es lo que hace

- Se he reescrito gran parte del código relacionado a la generación del mapa, así como también se añadió comentarios para que el código sea más legible.
- Se cambió la lógica basada en listas de escenas a una basada en "vecinos". Esto permitirá fácilmente hacer un seguimiento de qué escena debe ser renderizada cuando el jugador intente ir a través de alguna de las puertas.

### Por qué es necesario

El código iba a ser difícil de mantener a largo plazo en caso de querer añadir nuevas opciones, como las colisiones y el movimiento entre escenas.

### Issue(s) o PR(s) relacionados

Al haberse reescrito gran parte del código modificado en #12, este será reañadido en un segundo PR pronto.

---

_¡Muchas gracias a @amenes12, quien ayudó en la reescritura del código!_

2020-11-22 10:52 UTC, dalbitresb12 commented
@FrowsyFrog Creo que ya está listo para ser revisado. Todos los problemas conversados han sido arreglados. 😄

2020-11-22 14:56 UTC, FrowsyFrog requested changes
Me encantan los nuevos cambios! Lo único que faltaría sería revisar y corregir algunas cosas que dejé comentado 😄! Además, te aviso que necesitas agregar el cómo detectar el final del laberinto. En tu generación, no podrá ser la última escena generada la que será el final, debe ser la más lejana al punto de origen. Eso sería todo, espero los nuevos cambios para por fin hacer merge 👍

2020-11-22 14:56 UTC, FrowsyFrog commented on ZionEscape/Map.h
> +  const int maxScenes;
Tanto `seed` como `maxScenes` no puede ser `const`, ya que aparece un error al modificar su valor.

2020-11-22 14:56 UTC, FrowsyFrog commented on ZionEscape/Map.h
>      this->rnd = gcnew Random(seed);
Justo en esta parte es donde se ocasiona el error.

2020-11-22 14:56 UTC, FrowsyFrog commented on ZionEscape/Map.h
> +    this->depthCount = gcnew MinMax<short>(Defaults::Map::MinDepth, Defaults::Map::MaxDepth);
Aquí hay un pequeño error bastante fácil de corregir, Al `MinDepth` y `MaxDepth` estar siempre recibiendo valores por defecto, la generación del mapa se va a detener muchísimo antes de llegar al `maxCount`, presentando mapas muy pequeños. Para arreglar esto, te recomiendo relacionar el `MinDepth` y `MaxDepth` con la cantidad `min` y `max` de `maxScenes` y dividirlo entre 4, para que cada lado desde el inicio del laberinto, tenga el mismo `depth` y pueda generarse correctamente.

Ejemplo:

```csharp
 Map(int min, int max, int seed) {
    this->seed = seed;
    this->rnd = gcnew Random(seed);
    this->maxScenes = rnd->Next(min, max);
    this->depthCount = gcnew MinMax<short>(min/4,max/4);
    this->generated = false;
  }
```

2020-11-22 21:42 UTC, dalbitresb12 commented on ZionEscape/Map.h
> +    this->depthCount = gcnew MinMax<short>(Defaults::Map::MinDepth, Defaults::Map::MaxDepth);
Al ponerlo como un valor estático como mencionas (4, por ejemplo), el valor se hace demasiado pequeño en casos de escenarios con pocas escenas (10-20 escenas). Por lo tanto, decidí implementar una forma de evitar este problema permitiendo que mientras mayor sea la cantidad de escenas, mayor sea el número entre el que será dividido para obtener `depth`.

2020-11-22 21:44 UTC, dalbitresb12 commented
@FrowsyFrog Esta vez creo que ahora sí está listo. He visto una ligera mejora también en la rapidez de la generación y en la cantidad de uso de CPU. Además, he hecho que la generación del mapa sea ejecutada en un _thread_ diferente al principal para evitar bloquear la UI y permitir que otras línea de código sean ejecutadas al mismo tiempo que el mapa es generado usando la función recursiva.

2020-11-24 04:44 UTC, FrowsyFrog submitted a review, later dismissed
Parece ya prácticamente listo 😃 muy buen trabajo!

2020-11-24 17:52 UTC, FrowsyFrog approved these changes
Perfecto! No pudo quedar mejor! 🚀

2020-11-24 17:59 UTC, merged