[WIP] Created Sprite and Entity class
dalbitresb12/zion-escape pull request #4
Opened 2020-11-10 18:28 UTC by FrowsyFrog

### Qué es lo que hace

Se añaden las clases `Sprite` y `Entity` con sus respectivos métodos y atributos. 

### Por qué es necesario

Es necesario para poder añadir las demás clases faltantes que heredan de `Entity`, tales como `Player`, `Obstacle` o `NPC`.

### Issue(s) o PR(s) relacionados

Fixes #3 

### Contexto Adicional

Lista de cambios pendientes del Pull Request que necesita actualmente:
* Añadir los cambios del diagrama al código.
* Agregar comentarios.

2020-11-11 04:18 UTC, dalbitresb12 requested changes
Muy buen trabajo, solo cambia el nombre de la función que no está como en el [diagrama de clases](https://github.com/dalbitresb12/zion-escape/wiki/Diagrama-de-Clases) y estará listo. 😄

2020-11-11 04:18 UTC, dalbitresb12 commented on ZionEscape/Sprite.h
> +  Rectangle GetCrop() {
Debería ser `GetCropArea()`.

2020-11-11 04:18 UTC, dalbitresb12 commented on ZionEscape/Sprite.h
> +    world->DrawImage(image, this->drawingArea, this->GetCrop(), GraphicsUnit::Pixel);
No te olvides de cambiarlo también aquí.

2020-11-11 04:27 UTC, FrowsyFrog commented on ZionEscape/Sprite.h
> +  Rectangle GetCrop() {
Uy jaja, se me escapó. ¡Muchas gracias!

2020-11-11 04:46 UTC, dalbitresb12 approved these changes
¡Buen trabajo! 😄

2020-11-11 04:47 UTC, dalbitresb12 commented
@amenes12 @IzaYam Cuando tengan tiempo, le dan una revisada.

2020-11-11 15:44 UTC, amenes12 requested changes

2020-11-11 15:44 UTC, amenes12 commented on ZionEscape/Entity.h
> +    this->drawingArea.Y = pos.Y;
Podrías asignarlo como lo hiciste en la función `SetPosition()` de la clase Sprite: 
```cpp
this->drawingArea.Location = point;
```
Para mantener un estilo consistente en el código. 😄

2020-11-11 15:57 UTC, FrowsyFrog commented on ZionEscape/Entity.h
> +    this->drawingArea.Y = pos.Y;
Me parece bien! 👍  Ahora lo cambio :D

2020-11-12 00:58 UTC, dalbitresb12 commented
LGTM 👍. Merging.

2020-11-12 00:59 UTC, merged