[WIP] Generación de Mapa
dalbitresb12/zion-escape pull request #7
Opened 2020-11-14 23:28 UTC by FrowsyFrog

### Qué es lo que hace

Genera, por el momento en miniatura, los escenarios que darán forma al mapa (laberinto). 

### Por qué es necesario

Es necesario para el personaje, así como para los distintos enemigos y NPCs se generen en un espacio determinado. Además, limita al juego, es decir, establece un inicio y final para este.

2020-11-14 23:48 UTC, dalbitresb12 requested changes
Con esos cambios creo que quedaría perfecto. 😄

2020-11-14 23:48 UTC, dalbitresb12 commented on ZionEscape/Map.h
> +#include <list>
Este include no es necesario, solo necesitas el `namespace`.

2020-11-14 23:48 UTC, dalbitresb12 commented on ZionEscape/Map.h
> +    this->counter++;
Veo que usas este counter para mantener la cantidad de elementos que tiene la lista. Puedes usar directamente `scenes->Count`.

2020-11-14 23:48 UTC, dalbitresb12 commented on ZionEscape/SceneSpawner.h
> +  short opDir;
¿Puedes cambiar esto a un `enum`?

2020-11-14 23:48 UTC, dalbitresb12 commented on ZionEscape/Scene.h
> +  short id;
¿Podría ser también un `enum`?

2020-11-16 21:20 UTC, dalbitresb12 requested changes
Me parece genial los cambios. Más tarde los estaré probando en Visual Studio, pero voy dejando esos comentarios. Asimismo, en **todos los archivos de cabecera** por favor añade _header guards_. Es decir, si por ejemplo tenemos el archivo `Game.h`, justo después de la línea `#pragma once` añade lo siguiente:

```cpp
#pragma once

#ifndef _GAME_H_
#define _GAME_H_

/* todo el código, incluidos los `#include` y `using namespace` aquí */

#endif // !_GAME_H_
```

Finalmente, si se me ha pasado algún `enum`, también asegúrate que esté en el archivo [`Enums.h`](https://github.com/dalbitresb12/zion-escape/blob/main/ZionEscape/Enums.h).

2020-11-16 21:20 UTC, dalbitresb12 commented on ZionEscape/Scene.h
> +    this->drawingArea = Rectangle(pos.X, pos.Y, this->image->Width, this->image->Height);
Podrías usar el constructor de [Rectangle](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.rectangle.-ctor?view=netframework-4.8#System_Drawing_Rectangle__ctor_System_Drawing_Point_System_Drawing_Size_) que toma un `Point` y un `Size`.

```suggestion
    this->drawingArea = Rectangle(pos, this->image->Size);
```

2020-11-16 21:20 UTC, dalbitresb12 commented on ZionEscape/Scene.h
> +      delete this->spawners[i];
Mejor si lo haces con un `for each`.

```suggestion
    for each (SceneSpawner^ spawner in this->spawners)
      delete spawner;
```

2020-11-16 21:20 UTC, dalbitresb12 commented on ZionEscape/Scene.h
> +  void ImageSelector() {
En ninguna parte de esta función estás usando el `BitmapManager`.

2020-11-16 21:20 UTC, dalbitresb12 commented on ZionEscape/Scene.h
> +  }
Por si acaso, estaría mejor tener alguna validación.

```suggestion
  void DeleteSpawner(short n) {
    if (n >= 0 && n < this->spawners->Count)
      this->spawners->Remove(this->spawners[n]);
  }
```

2020-11-16 21:20 UTC, dalbitresb12 commented on ZionEscape/SceneSpawner.h
> +};
Mueve este `enum` al archivo [`Enums.h`](https://github.com/dalbitresb12/zion-escape/blob/main/ZionEscape/Enums.h), por favor.

2020-11-16 21:40 UTC, FrowsyFrog commented on ZionEscape/Scene.h
> +    this->drawingArea = Rectangle(pos.X, pos.Y, this->image->Width, this->image->Height);
Hola, gracias por las mejoras mencionadas! Respecto a lo de añadir los *header guards*, ¿no cumpliría la misma función que el `#pragma once`?

2020-11-16 22:04 UTC, dalbitresb12 commented on ZionEscape/Scene.h
> +    this->drawingArea = Rectangle(pos.X, pos.Y, this->image->Width, this->image->Height);
`#pragma once` es una directiva incluida en compiladores recientes que hace eso mismo. Aun así, he decidido añadir los _header guards_ a todos los archivos debido a unas dependencias circulares que se estaban generando.

2020-11-16 22:07 UTC, FrowsyFrog commented on ZionEscape/Scene.h
> +  }
Me parece que la verificación no es necesaria. Ya que el método recibe, en un momento determinado, un parámetro en específico (*en este caso `n`*), por lo que obligatoriamente ese `spawner` va a existir.

2020-11-18 15:44 UTC, amenes12 approved these changes
Me gusta lo que veo buen hombre. Gran trabajo:)

2020-11-18 16:09 UTC, dalbitresb12 approved these changes
LGTM. 😄 Merging.

2020-11-18 16:09 UTC, merged